server:
  port: 8701

spring:
  datasource:
    url: jdbc:mysql://cnj-account-mysql:3306/account?useSSL=false&allowPublicKeyRetrieval=true
    username: dbuser
    password: dbp4ss
    platform: mysql
  jackson:
    serialization:
      indent-output: true
